# =========================
# Red compartida
# =========================
networks:
  checkin-net:
    driver: bridge

# =========================
# Volúmenes persistentes
# =========================
volumes:
  empleados-db-data:
  departamentos-db-data:
  auth-db-data:
  notificaciones-db-data:
  perfiles-db-data:

services:
  # ==================================================
  # BASE DE DATOS - EMPLEADOS
  # ==================================================
  database-empleados:
    image: postgres:16
    container_name: database-empleados
    environment:
      POSTGRES_DB: empleados_db
      POSTGRES_USER: empleados_user
      POSTGRES_PASSWORD: empleados_pass
    volumes:
      - empleados-db-data:/var/lib/postgresql/data
    networks:
      - checkin-net
    ports:
      - "5437:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U empleados_user -d empleados_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==================================================
  # SERVICIO - EMPLEADOS
  # ==================================================
  empleados-service:
    build: ./empleados-service
    container_name: empleados-service
    environment:
      DB_HOST: database-empleados
      DB_PORT: 5432
      DB_NAME: empleados_db
      DB_USER: empleados_user
      DB_PASSWORD: empleados_pass
      DEPARTAMENTOS_SERVICE_URL: http://departamentos-service:8081
      RABBITMQ_HOST: message-broker
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin
      JWT_SECRET: supersecretosupersecretosupersecreto
      JWT_ALGORITHM: HS256
    depends_on:
      database-empleados:
        condition: service_healthy
    networks:
      - checkin-net
    ports:
      - "8080:80"

  # ==================================================
  # BASE DE DATOS - DEPARTAMENTOS
  # ==================================================
  database-departamentos:
    image: postgres:16
    container_name: database-departamentos
    environment:
      POSTGRES_DB: departamentos_db
      POSTGRES_USER: departamentos_user
      POSTGRES_PASSWORD: departamentos_pass
    volumes:
      - departamentos-db-data:/var/lib/postgresql/data
    networks:
      - checkin-net
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U departamentos_user -d departamentos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==================================================
  # BASE DE DATOS - AUTH
  # ==================================================
  database-auth:
    image: postgres:16
    container_name: database-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - checkin-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==================================================
  # SERVICIO - DEPARTAMENTOS
  # ==================================================
  departamentos-service:
    build: ./departamentos-service
    container_name: departamentos-service
    environment:
      DB_HOST: database-departamentos
      DB_PORT: 5432
      DB_NAME: departamentos_db
      DB_USER: departamentos_user
      DB_PASSWORD: departamentos_pass
      JWT_SECRET: supersecretosupersecretosupersecreto
      JWT_ALGORITHM: HS256
    depends_on:
      database-departamentos:
        condition: service_healthy
    networks:
      - checkin-net
    ports:
      - "8086:8081"

  # ==================================================
  # SERVICIO - AUTH / JWT
  # ==================================================
  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      DB_HOST: database-auth
      DB_PORT: 5432
      DB_NAME: auth_db
      DB_USER: auth_user
      DB_PASSWORD: auth_pass
      JWT_SECRET: supersecretosupersecretosupersecreto
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRES_MINUTES: 15
      RESET_TOKEN_EXPIRES_MINUTES: 60
      RABBITMQ_URL: amqp://admin:admin@message-broker:5672
      AUTH_ADMIN_USER: admin
      AUTH_ADMIN_PASSWORD: admin123
      AUTH_DEFAULT_USER: user
      AUTH_DEFAULT_PASSWORD: user123
    depends_on:
      database-auth:
        condition: service_healthy
      message-broker:
        condition: service_started
    networks:
      - checkin-net
    ports:
      - "8082:80"

  # ... (tus servicios anteriores) ...

  # ==================================================
  # MESSAGE BROKER (RabbitMQ) - [cite: 29, 31]
  # ==================================================
  message-broker:
    image: rabbitmq:3-management
    container_name: message-broker
    ports:
      - "5672:5672"   # Puerto de mensajería
      - "15672:15672" # Interfaz UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - checkin-net

  
  # ==================================================
  # BASE DE DATOS - NOTIFICACIONES (Reto 3)
  # ==================================================
  database-notificaciones:
    image: postgres:16
    container_name: database-notificaciones
    environment:
      POSTGRES_DB: notificaciones_db
      POSTGRES_USER: notificaciones_user
      POSTGRES_PASSWORD: notificaciones_pass
    volumes:
      - notificaciones-db-data:/var/lib/postgresql/data
    networks:
      - checkin-net
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notificaciones_user -d notificaciones_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==================================================
  # SERVICIO - NOTIFICACIONES (Reto 3 / .NET)
  # ==================================================
  notificaciones-service:
    build: ./notificaciones-service
    container_name: notificaciones-service
    environment:
      ConnectionStrings__DefaultConnection: "Host=database-notificaciones;Port=5432;Database=notificaciones_db;Username=notificaciones_user;Password=notificaciones_pass"
      RabbitMQ__Host: message-broker
      RabbitMQ__Port: 5672
      RabbitMQ__User: admin
      RabbitMQ__Password: admin
    depends_on:
      database-notificaciones:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    networks:
      - checkin-net
    ports:
      - "8084:8084"

 # ==================================================
  # BASE DE DATOS - PERFILES (Reto 3)
  # ==================================================
  database-perfiles:
    image: postgres:16
    container_name: database-perfiles
    environment:
      POSTGRES_DB: perfiles_db
      POSTGRES_USER: perfiles_user
      POSTGRES_PASSWORD: perfiles_pass
    volumes:
      - perfiles-db-data:/var/lib/postgresql/data
    networks:
      - checkin-net
    ports:
      - "5439:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U perfiles_user -d perfiles_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==================================================
  # SERVICIO - PERFILES (Reto 3 / Spring Boot)
  # ==================================================
  perfiles-service:
    build: ./perfiles-service
    container_name: perfiles-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-perfiles:5432/perfiles_db
      SPRING_DATASOURCE_USERNAME: perfiles_user
      SPRING_DATASOURCE_PASSWORD: perfiles_pass
      SPRING_RABBITMQ_HOST: message-broker
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
      JWT_SECRET: supersecretosupersecretosupersecreto
      JWT_ALGORITHM: HS256
    depends_on:
      database-perfiles:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    networks:
      - checkin-net
    ports:
      - "8083:8083"